{
 "title": "Rundeck",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance_address", "label": "instance_address", "query": { "query": "label_values(instance_address)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_uptime_since{instance_address=\"$instance_address\"}"
    }
   ]
  },
  {
   "title": "Scheduled Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_scheduler_quartz_scheduledJobs{instance_address=\"$instance_address\"}"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_scheduler_running{instance_address=\"$instance_address\"}"
    }
   ]
  },
  {
   "title": "Top 10 Failed Jobs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(rundeck_project_execution_status{instance_address=\"$instance_address\", status=\"failed\"}[$__range])) by (project_name, job_name))",
     "legendFormat": "{{project_name}} - {{job_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Job Duration",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, avg(rundeck_project_execution_duration_seconds{instance_address=\"$instance_address\"}) by (project_name,job_name)) > 0",
     "legendFormat": "{{project_name}} - {{job_name}}"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rundeck_api_requests_requestTimer_total{instance_address=~\"$instance_address\"} or rundeck_api_requests_requestTimer_count{instance_address=~\"$instance_address\"})"
    }
   ]
  },
  {
   "title": "Web Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs((rundeck_api_requests_requestTimer_total{instance_address=~\"$instance_address\"} or rundeck_api_requests_requestTimer_count{instance_address=~\"$instance_address\"}) - (rundeck_web_requests_requestTimer_total{instance_address=~\"$instance_address\"} or rundeck_web_requests_requestTimer_count{instance_address=~\"$instance_address\"}))"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_scheduler_threadPoolSize{instance_address=\"$instance_address\"}",
     "legendFormat": "Thread Pool Size"
    },
    {
     "expr": "rundeck_system_stats_threads_active{instance_address=\"$instance_address\"}",
     "legendFormat": "Threads active"
    }
   ]
  },
  {
   "title": "Top 10 Running Jobs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, max(rundeck_project_execution_status{instance_address=\"$instance_address\", status=\"running\"}) by (project_name, job_name))",
     "legendFormat": "{{project_name}} - {{job_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rundeck_system_stats_memory_free_bytes{instance_address=\"$instance_address\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "rundeck_system_stats_memory_total_bytes{instance_address=\"$instance_address\"} - rundeck_system_stats_memory_free_bytes{instance_address=\"$instance_address\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "rundeck_system_stats_memory_max_bytes{instance_address=\"$instance_address\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rundeck_system_stats_cpu_loadAverage_ratio{instance_address=\"$instance_address\"}",
     "legendFormat": "Load average"
    }
   ]
  }
 ]
}