{
 "title": "Rundeck",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_uptime_since{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Scheduled Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_scheduler_quartz_scheduledJobs{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_scheduler_running{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Top 10 Failed Jobs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(rundeck_project_execution_status{instance=\"$instance\", status=\"failed\"} > 0) by (project_name, job_name))",
     "legendFormat": "{{project_name}} - {{job_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Job Duration",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(rundeck_project_execution_duration_seconds{instance=\"$instance\"}) by (project_name,job_name)) > 0",
     "legendFormat": "{{project_name}} - {{job_name}}"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_api_requests_requestTimer_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Web Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(rundeck_api_requests_requestTimer_total{instance=\"$instance\"} - rundeck_web_requests_requestTimer_total{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_scheduler_threadPoolSize{instance=\"$instance\"}",
     "legendFormat": "Thread Pool Size"
    },
    {
     "expr": "rundeck_system_stats_threads_active{instance=\"$instance\"}",
     "legendFormat": "Threads active"
    }
   ]
  },
  {
   "title": "Top 10 Running Jobs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(rundeck_project_execution_status{instance=\"$instance\", status=\"running\"} > 0) by (project_name, job_name))",
     "legendFormat": "{{project_name}} - {{job_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rundeck_system_stats_memory_free_bytes{instance=\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "rundeck_system_stats_memory_total_bytes{instance=\"$instance\"} - rundeck_system_stats_memory_free_bytes{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "rundeck_system_stats_memory_max_bytes{instance=\"$instance\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rundeck_system_stats_cpu_loadAverage_ratio{instance=\"$instance\"}",
     "legendFormat": "Load average"
    }
   ]
  }
 ]
}